#!/usr/bin/env python3
"""NEC infrared stimulus for bio-sim.

Writes a JSONC config that feeds `nec_rx` the gpio_in edges an IR receiver
produces for a NEC frame; run it with ./container-run and check the fifo_drain
output against the expected words in the config header.

The receiver idles high and pulls low for each burst, so nec_rx sees a rising
edge at every burst end. Thresholds reach the program in BIO clock ticks, so
the 7MHz default fclk compresses a 67.5ms frame to 470k cycles.
"""
import argparse, json, re, sys


def num(s):
    return int(s, 0)


ap = argparse.ArgumentParser()
ap.add_argument("--file", metavar="CONFIG", default="-",
                help="write JSONC config here ('-' = stdout, the default)")
ap.add_argument("--addr-lo", type=num, default=0x85, help="first address byte")
ap.add_argument("--addr-hi", type=num, default=0xFE, help="second address byte")
ap.add_argument("--command", type=num, default=0x43, help="command byte")
ap.add_argument("--repeats", type=int, default=1, help="repeat frames after the data frame")
ap.add_argument("--pin", type=int, default=24, help="gpio the receiver drives")
ap.add_argument("--fclk", type=float, default=7e6, help="declared fclk in Hz")
ap.add_argument("--firmware", default="sw/nec_rx/nec_rx.bin")
ap.add_argument("--trace", default="nec_rx.fst")
a = ap.parse_args()

# protocol timing, microseconds
LEADER_BURST, LEADER_SPACE = 9000, 4500
REPEAT_SPACE = 2250
BURST, SPACE0, SPACE1 = 560, 560, 1690
FRAME_PERIOD = 108000

# decode boundaries, us: noise | bit 0 | bit 1 | repeat | leader | idle
BOUNDS_US = [700, 1685, 2530, 3935, 6500]


def ticks(us):
    return round(us * a.fclk / 1e6)


events = [(0, a.pin, 1)]  # the receiver idles high


def burst(t, us_len):
    """Pull low for us_len, then release; returns the rising edge time."""
    events.append((t, a.pin, 0))
    t += ticks(us_len)
    events.append((t, a.pin, 1))
    return t


frame_start = ticks(1000)  # idle before the first frame
t = burst(frame_start, LEADER_BURST) + ticks(LEADER_SPACE)
for byte in (a.addr_lo, a.addr_hi, a.command, ~a.command & 0xFF):
    for i in range(8):  # LSB first on the wire
        t = burst(t, BURST) + ticks(SPACE1 if byte >> i & 1 else SPACE0)
t = burst(t, BURST)  # stop burst terminates the last bit

for _ in range(a.repeats):
    frame_start += ticks(FRAME_PERIOD)
    t = burst(frame_start, LEADER_BURST) + ticks(REPEAT_SPACE)
    t = burst(t, BURST)

total = t + ticks(FRAME_PERIOD)  # let the idle gap expire

# one word per frame: [addr lo, addr hi, cmd, ~cmd] little-endian, 0xffffffff for a repeat
frame = a.addr_lo | a.addr_hi << 8 | a.command << 16 | (~a.command & 0xFF) << 24
expected = [frame] + [0xFFFFFFFF] * a.repeats

cfg = {
    "fclk_mhz": a.fclk / 1e6,
    "trace": {"file": a.trace},
    "commands": [
        {"cmd": "load", "core": 0, "bin": a.firmware},
        {"cmd": "clock", "core": 0, "style": "external", "pin": a.pin},
        # pin mask, then the five boundaries in ticks
        {"cmd": "fifo_write", "bank": 0,
         "data": [1 << a.pin] + [ticks(us) for us in BOUNDS_US]},
        {"cmd": "start", "cores": [0]},
        {"cmd": "inject",
         "events": [{"cycle": c, "pin": p, "value": v} for c, p, v in events]},
        {"cmd": "run", "cycles": total, "stop_on_trap": False},
        {"cmd": "fifo_drain", "bank": 0},
    ],
}

hdr = (f"// GENERATED by clients/nec.py - address {a.addr_lo:02x} {a.addr_hi:02x}, "
       f"command {a.command:02x}, {a.repeats} repeat frame(s)\n"
       f"// expected FIFO0 words: {', '.join(f'0x{w:08x}' for w in expected)}\n")

# one edge per line, rather than four
text = re.sub(r'\{\s*"cycle": (\d+),\s*"pin": (\d+),\s*"value": (\d+)\s*\}',
              r'{ "cycle": \1, "pin": \2, "value": \3 }', json.dumps(cfg, indent=2))

f = sys.stdout if a.file == "-" else open(a.file, "w")
f.write(hdr)
f.write(text)
f.write("\n")
if f is not sys.stdout:
    f.close()
    print(f"wrote {a.file} ({len(events)} edges, {total} cycles)", file=sys.stderr)
