// AUTOGENERATED CODE on 2026-06-07T13:57:49.082160 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(blink_bio_code, BM_BLINK_BIO_START, BM_BLINK_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "li	a1, 0",
    "lui	a0, 512",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a1",
    // --- inline asm end ---
    "li	a2, 2000",
    "22:", // .LBB1_1: =>This Loop Header: Depth=1
    // Child Loop BB1_3 Depth 2
    // --- inline asm begin ---
    "mv	x22, a0",
    // --- inline asm end ---
    "addi	a1, a1, 1",
    "bne	a1, a2, 22b",
    // in Loop: Header=BB1_1 Depth=1
    "li	a3, 2000",
    "23:", // .LBB1_3: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "li	a1, 0",
    // --- inline asm begin ---
    "mv	x23, a1",
    // --- inline asm end ---
    "addi	a3, a3, -1",
    "bnez	a3, 23b",
    "j	22b"
);
