// AUTOGENERATED CODE on 2026-06-06T21:54:16.740778 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(invert_bio_code, BM_INVERT_BIO_START, BM_INVERT_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "li	a1, 3",
    "li	a0, 2",
    // --- inline asm begin ---
    "mv	x26, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "li	a1, 1",
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    "li	a1, 0",
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "mv	a2, x21",
    // --- inline asm end ---
    "andi	a2, a2, 1",
    "bnez	a2, 23f",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x22, a0",
    // --- inline asm end ---
    "j	22b",
    "23:", // .LBB1_3: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x23, a1",
    // --- inline asm end ---
    "j	22b"
);
