// AUTOGENERATED CODE on 2026-06-27T23:22:03.631691 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(core1_bio_code, BM_CORE1_BIO_START, BM_CORE1_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "addi	a0, a0, 1",
    // --- inline asm begin ---
    "mv	x16, a0",
    // --- inline asm end ---
    "j	22b"
);
