// AUTOGENERATED CODE on 2026-06-27T23:21:58.798468 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(core0_bio_code, BM_CORE0_BIO_START, BM_CORE0_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "li	a0, 0",
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "mv	x17, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x16",
    // --- inline asm end ---
    "addi	a0, a0, 1",
    "j	22b"
);
