// AUTOGENERATED CODE on 2026-06-07T14:01:15.675585 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(test_ws2812_bio_code, BM_TEST_WS2812_BIO_START, BM_TEST_WS2812_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "sw	a0, 0(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	s1, x17",
    // --- inline asm end ---
    "lui	s0, %hi(39f)",
    "addi	s0, s0, %lo(39f)",
    "34:", // .LBB3_1: =>This Loop Header: Depth=1
    // Child Loop BB3_2 Depth 2
    // Child Loop BB3_7 Depth 2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "35:", // .LBB3_2: Parent Loop BB3_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a0, a0, 5",
    "bgez	a0, 37f",
    // in Loop: Header=BB3_2 Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 36f",
    // in Loop: Header=BB3_2 Depth=2
    "slli	a1, a0, 1",
    "slli	a0, a0, 8",
    "srli	a1, a1, 25",
    "sltiu	a2, a1, 100",
    "addi	a2, a2, -1",
    "andi	a2, a2, -100",
    "add	a1, a1, a2",
    "srli	a0, a0, 8",
    "slli	a1, a1, 2",
    "add	a1, a1, s0",
    "sw	a0, 0(a1)",
    "36:", // .LBB3_5: in Loop: Header=BB3_2 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "j	35b",
    "37:", // .LBB3_6: in Loop: Header=BB3_1 Depth=1
    "lw	a0, 0(sp)", // 4-byte Folded Reload
    "mv	a1, s0",
    "mv	a2, s1",
    "jal	ra, 21b",
    "li	a0, 20",
    "38:", // .LBB3_7: Parent Loop BB3_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a0, a0, -1",
    "bnez	a0, 38b",
    "j	34b",
    // --- rodata: led_buf (400 entries, 100 words) ---
    ".p2align 2",
    "39:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000", // [60] 0, 0, 0, 0
    ".word 0x00000000", // [64] 0, 0, 0, 0
    ".word 0x00000000", // [68] 0, 0, 0, 0
    ".word 0x00000000", // [72] 0, 0, 0, 0
    ".word 0x00000000", // [76] 0, 0, 0, 0
    ".word 0x00000000", // [80] 0, 0, 0, 0
    ".word 0x00000000", // [84] 0, 0, 0, 0
    ".word 0x00000000", // [88] 0, 0, 0, 0
    ".word 0x00000000", // [92] 0, 0, 0, 0
    ".word 0x00000000", // [96] 0, 0, 0, 0
    ".word 0x00000000", // [100] 0, 0, 0, 0
    ".word 0x00000000", // [104] 0, 0, 0, 0
    ".word 0x00000000", // [108] 0, 0, 0, 0
    ".word 0x00000000", // [112] 0, 0, 0, 0
    ".word 0x00000000", // [116] 0, 0, 0, 0
    ".word 0x00000000", // [120] 0, 0, 0, 0
    ".word 0x00000000", // [124] 0, 0, 0, 0
    ".word 0x00000000", // [128] 0, 0, 0, 0
    ".word 0x00000000", // [132] 0, 0, 0, 0
    ".word 0x00000000", // [136] 0, 0, 0, 0
    ".word 0x00000000", // [140] 0, 0, 0, 0
    ".word 0x00000000", // [144] 0, 0, 0, 0
    ".word 0x00000000", // [148] 0, 0, 0, 0
    ".word 0x00000000", // [152] 0, 0, 0, 0
    ".word 0x00000000", // [156] 0, 0, 0, 0
    ".word 0x00000000", // [160] 0, 0, 0, 0
    ".word 0x00000000", // [164] 0, 0, 0, 0
    ".word 0x00000000", // [168] 0, 0, 0, 0
    ".word 0x00000000", // [172] 0, 0, 0, 0
    ".word 0x00000000", // [176] 0, 0, 0, 0
    ".word 0x00000000", // [180] 0, 0, 0, 0
    ".word 0x00000000", // [184] 0, 0, 0, 0
    ".word 0x00000000", // [188] 0, 0, 0, 0
    ".word 0x00000000", // [192] 0, 0, 0, 0
    ".word 0x00000000", // [196] 0, 0, 0, 0
    ".word 0x00000000", // [200] 0, 0, 0, 0
    ".word 0x00000000", // [204] 0, 0, 0, 0
    ".word 0x00000000", // [208] 0, 0, 0, 0
    ".word 0x00000000", // [212] 0, 0, 0, 0
    ".word 0x00000000", // [216] 0, 0, 0, 0
    ".word 0x00000000", // [220] 0, 0, 0, 0
    ".word 0x00000000", // [224] 0, 0, 0, 0
    ".word 0x00000000", // [228] 0, 0, 0, 0
    ".word 0x00000000", // [232] 0, 0, 0, 0
    ".word 0x00000000", // [236] 0, 0, 0, 0
    ".word 0x00000000", // [240] 0, 0, 0, 0
    ".word 0x00000000", // [244] 0, 0, 0, 0
    ".word 0x00000000", // [248] 0, 0, 0, 0
    ".word 0x00000000", // [252] 0, 0, 0, 0
    ".word 0x00000000", // [256] 0, 0, 0, 0
    ".word 0x00000000", // [260] 0, 0, 0, 0
    ".word 0x00000000", // [264] 0, 0, 0, 0
    ".word 0x00000000", // [268] 0, 0, 0, 0
    ".word 0x00000000", // [272] 0, 0, 0, 0
    ".word 0x00000000", // [276] 0, 0, 0, 0
    ".word 0x00000000", // [280] 0, 0, 0, 0
    ".word 0x00000000", // [284] 0, 0, 0, 0
    ".word 0x00000000", // [288] 0, 0, 0, 0
    ".word 0x00000000", // [292] 0, 0, 0, 0
    ".word 0x00000000", // [296] 0, 0, 0, 0
    ".word 0x00000000", // [300] 0, 0, 0, 0
    ".word 0x00000000", // [304] 0, 0, 0, 0
    ".word 0x00000000", // [308] 0, 0, 0, 0
    ".word 0x00000000", // [312] 0, 0, 0, 0
    ".word 0x00000000", // [316] 0, 0, 0, 0
    ".word 0x00000000", // [320] 0, 0, 0, 0
    ".word 0x00000000", // [324] 0, 0, 0, 0
    ".word 0x00000000", // [328] 0, 0, 0, 0
    ".word 0x00000000", // [332] 0, 0, 0, 0
    ".word 0x00000000", // [336] 0, 0, 0, 0
    ".word 0x00000000", // [340] 0, 0, 0, 0
    ".word 0x00000000", // [344] 0, 0, 0, 0
    ".word 0x00000000", // [348] 0, 0, 0, 0
    ".word 0x00000000", // [352] 0, 0, 0, 0
    ".word 0x00000000", // [356] 0, 0, 0, 0
    ".word 0x00000000", // [360] 0, 0, 0, 0
    ".word 0x00000000", // [364] 0, 0, 0, 0
    ".word 0x00000000", // [368] 0, 0, 0, 0
    ".word 0x00000000", // [372] 0, 0, 0, 0
    ".word 0x00000000", // [376] 0, 0, 0, 0
    ".word 0x00000000", // [380] 0, 0, 0, 0
    ".word 0x00000000", // [384] 0, 0, 0, 0
    ".word 0x00000000", // [388] 0, 0, 0, 0
    ".word 0x00000000", // [392] 0, 0, 0, 0
    ".word 0x00000000" // [396] 0, 0, 0, 0
);
