// AUTOGENERATED CODE on 2026-07-05T16:10:24.606917 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(i2s_bio_code, BM_I2S_BIO_START, BM_I2S_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "li	a5, 0",
    "li	a0, 14",
    "li	a2, 6",
    "li	a3, 8",
    "li	t2, 32",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a2",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a2",
    // --- inline asm end ---
    "li	t0, 2",
    "li	a3, 4",
    "li	a4, 25",
    "li	t1, 1",
    "li	a0, 0",
    "li	a2, 0",
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beq	a0, t2, 24f",
    // in Loop: Header=BB1_1 Depth=1
    "beq	a0, t1, 23f",
    // in Loop: Header=BB1_1 Depth=1
    "bnez	a0, 25f",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x23, a5",
    // --- inline asm end ---
    "j	25f",
    "23:", // .LBB1_5: in Loop: Header=BB1_1 Depth=1
    "li	a2, 0",
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x22, t0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x23, a5",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x21",
    // --- inline asm end ---
    "slli	a1, a1, 28",
    // --- inline asm begin ---
    "mv	x22, a3",
    // --- inline asm end ---
    "srli	a1, a1, 31",
    "or	a1, a1, a2",
    "slli	a2, a1, 1",
    "bne	a0, a4, 26f",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x16, a2",
    // --- inline asm end ---
    "26:", // .LBB1_9: in Loop: Header=BB1_1 Depth=1
    "addi	a0, a0, 1",
    "srai	a1, a0, 31",
    "srli	a1, a1, 26",
    "add	a1, a1, a0",
    "andi	a1, a1, -64",
    "sub	a0, a0, a1",
    "j	22b"
);
